### ISSUE TITLE
Link to install binaries is reporting a internal error

### ISSUE THREAD

**Issue by mateMathieu** [kanatzidis/Wells#3]
Very useful software, it is just a shame to have an error while using the provided link to download the binary in the Readme.md.

**Comment by kanatzidis** [comment]
Thank you for letting me know about that! I have made the binary available on the GitHub release page and updated the readme.

**Comment by mateMathieu** [comment]
Thank you!
Funny you reply now, I am just getting to finalize a solution to visualize mac... in order to restore my time machine. XD
